export { default } from "./src/wallet-manager-ton.js";
export { default as WalletAccountReadOnlyTon } from "./src/wallet-account-read-only-ton.js";
export { default as WalletAccountTon } from "./src/wallet-account-ton.js";
export type TonTransactionReceipt = import("@ton/ton").Transaction;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferOptions = import("@tetherto/wdk-wallet").TransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type Finality = import("@tetherto/wdk-wallet").Finality;
export type TransactionReceipt = import("@tetherto/wdk-wallet").TransactionReceipt;
export type WaitForTransactionTarget = import("@tetherto/wdk-wallet").WaitForTransactionTarget;
export type WaitForTransactionOptions = import("@tetherto/wdk-wallet").WaitForTransactionOptions;
export type TonTransaction = import("./src/wallet-account-ton.js").TonTransaction;
export type TonTransactionDetails = import("./src/wallet-account-read-only-ton.js").TonTransactionDetails;
export type TonClientConfig = import("./src/wallet-account-ton.js").TonClientConfig;
export type TonWalletConfig = import("./src/wallet-account-ton.js").TonWalletConfig;
